Add rmw_publisher_wait_for_all_acked support
ros2/rmw pull request #296
Opened 2020-12-24 09:40 UTC by Barry-Xu-2018

Signed-off-by: Barry Xu <Barry.Xu@sony.com>

2020-12-24 09:41 UTC, Barry-Xu-2018 commented
Related to #295

2021-01-05 05:20 UTC, fujitatomoya requested changes
as far as i see, rmw_connext / rmw_fastftps / rmw_cyclonedds all support `wait_for_acknowledgments`.

2021-01-05 05:20 UTC, fujitatomoya commented on rmw/include/rmw/rmw.h
> + *
I believe this relies on DDS API to wait for acknowledgments in a DataWriter. (described [DDS v1.4 spec](https://www.omg.org/spec/DDS/1.4/PDF) 2.2.2.4.2.15 wait_for_acknowledgments) So that it only works effectively when RELIABILITY QoS kind set to RELIABLE, not for BEST_EFFORT. I think this should be described explicitly.

2021-01-05 05:53 UTC, Barry-Xu-2018 commented on rmw/include/rmw/rmw.h
> + *
Yeah. It is important.  
I will add a note to describe this.

2021-03-25 16:42 UTC, ivanpauno reviewed
LGTM!

I've left some minor comments

2021-03-25 16:42 UTC, ivanpauno commented on rmw/include/rmw/rmw.h
> +/// Waits until all published message data were acknowledged or timeout.
nit: minimal rewording

```suggestion
/// Wait until all published message data is acknowledged or until the specified timeout elapses.
```

2021-03-25 16:42 UTC, ivanpauno commented on rmw/include/rmw/rmw.h
> + *
It would be good to document what happens for a best effort publisher.
In that case I think the function should be a no-op and not fail.

2021-03-25 16:42 UTC, ivanpauno commented on rmw/include/rmw/rmw.h
> +  const rmw_time_t * wait_timeout);
it would be great if dds provided this for a `participant`, so you don't have to individually call the function in all reliable publishers, but that doesn't seem to be the case.

2021-03-25 16:42 UTC, ivanpauno commented on rmw/include/rmw/rmw.h
> +  const rmw_time_t * wait_timeout);
```suggestion
rmw_publisher_wait_for_all_acked(
  const rmw_publisher_t * publisher,
  rmw_time_t wait_timeout);
```

dds timeout seems to be mandatory, not optional.
If you want you can keep the const *, but passing `NULL` should be an error

2021-03-25 23:35 UTC, fujitatomoya commented on rmw/include/rmw/rmw.h
> + *
totally agree.

2021-03-26 09:06 UTC, Barry-Xu-2018 commented on rmw/include/rmw/rmw.h
> +  const rmw_time_t * wait_timeout);
Yeah.

2021-03-26 09:14 UTC, Barry-Xu-2018 commented on rmw/include/rmw/rmw.h
> +  const rmw_time_t * wait_timeout);
Yeah. Will update it.  
Thanks

2021-03-26 09:35 UTC, iuhilnehc-ynos commented on rmw/include/rmw/rmw.h
> +  const rmw_time_t * wait_timeout);
I think we could keep the same behavior as https://github.com/ros2/rmw/blob/150bbc9871ddfcb998befe7444bd1112baef61b1/rmw/include/rmw/rmw.h#L2452-L2454

2021-03-26 12:56 UTC, ivanpauno approved these changes
LGTM!

2021-03-26 12:56 UTC, ivanpauno commented on rmw/include/rmw/rmw.h
> + * \note This function only works effectively while QOS profile of publisher is set to RELIABLE.
nit:
```suggestion
 * This function only works effectively while QOS profile of publisher is set to RELIABLE.
```

2021-03-26 12:56 UTC, ivanpauno commented on rmw/include/rmw/rmw.h
> + *   data. Else, this represents the maximum amount of time to wait for all published message data
```suggestion
 * \param[in] wait_timeout represents the maximum amount of time to wait for all published message data
```

Clarifying what happens for timeout zero doesn't seem to be worth it.
The DDS `wait_for_acknowledgments()` function likely returns immediately and doesn't check anything in that case.

2021-03-26 12:56 UTC, ivanpauno commented on rmw/include/rmw/rmw.h
> +  const rmw_time_t wait_timeout);
`const` doesn't help here.

```suggestion
  rmw_time_t wait_timeout);
```

2021-03-26 12:57 UTC, ivanpauno commented
The next step is to complete the implementations for `rmw_fastrtps`, `rmw_cyclonedds`, `rmw_connextdds`.

2021-03-28 00:52 UTC, Barry-Xu-2018 commented
> The next step is to complete the implementations for rmw_fastrtps, rmw_cyclonedds, rmw_connextdds. 

Yeah. I will implement them.

2021-03-28 12:05 UTC, fujitatomoya approved these changes
i am good to go.

2021-03-31 15:40 UTC, hidmic commented on rmw/include/rmw/rmw.h
> + * <i>[1] rmw implementation defined, check the implementation documentation</i>
@Barry-Xu-2018 if I may, I'd suggest we fully characterize runtime behavior, thread safety, and preconditions/postconditions as in e.g. `rmw_publish_serialized_message()`.

2021-04-01 09:57 UTC, Barry-Xu-2018 commented on rmw/include/rmw/rmw.h
> + * <i>[1] rmw implementation defined, check the implementation documentation</i>
@hidmic 

While describing runtime behavior, thread safety, I have some confusion. I think these points cover the behavior of rmw layer + DDS. But I have no enough information for all DDS.  So I confuse how to describe them.   

For example,
```
 Thread-safety
 *   Publishers are thread-safe objects, and so are all operations on them except for finalization.
 *   Therefore, it is safe to return borrowed ROS messages to the same publisher concurrently.
 *   However, since ownership of the loaned ROS message is given back to the middleware and
 *   this transfer is not synchronized, it is not safe to return the same loaned ROS message
 *   concurrently.
 
 RMW_PUBLIC
RMW_WARN_UNUSED
rmw_ret_t
rmw_return_loaned_message_from_publisher(
  const rmw_publisher_t * publisher,
  void * loaned_message);
```

rmw_return_loaned_message_from_publisher() will call interface of different DDS. We cannot make a judgement  on whether the interface is thread-safety or not because DDS have different implementation.   

For rmw_publisher_wait_for_all_acked(), the rmw implementation is to directly call corresponding interface of DDS (refer to https://github.com/ros2/rmw_cyclonedds/pull/294/files).  How to describe thread-safety ?

2021-04-04 22:32 UTC, wjwwood commented on rmw/include/rmw/rmw.h
> + * this function will immediately return RMW_RET_OK.
```suggestion
 * This function only works effectively while QOS profile of publisher is set to RELIABLE.
 * Otherwise this function will immediately return RMW_RET_OK.
```

2021-04-04 22:32 UTC, wjwwood commented on rmw/include/rmw/rmw.h
> + * this function will immediately return RMW_RET_OK.
nitpick: please use one sentence per line

> - [any] Each sentence must start on a new line.
>   - Rationale: For longer paragraphs a single change in the beginning makes the diff unreadable since it carries forward through the whole paragraph.

https://docs.ros.org/en/rolling/Contributing/Code-Style-Language-Versions.html#markdown-restructured-text-docblocks

2021-04-04 22:32 UTC, wjwwood commented on rmw/include/rmw/rmw.h
> + * <i>[1] rmw implementation defined, check the implementation documentation</i>
I have some doubt about this too.

I think, rather than being concerned with this:

> rmw_return_loaned_message_from_publisher() will call interface of different DDS. We cannot make a judgement on whether the interface is thread-safety or not because DDS have different implementation.
>
> For rmw_publisher_wait_for_all_acked(), the rmw implementation is to directly call corresponding interface of DDS (refer to https://github.com/ros2/rmw_cyclonedds/pull/294/files). How to describe thread-safety ?

We should be worried about what can the caller of this function expect. If it is not thread-safe, then they need to know what synchronization issues exist, and how to avoid them. For this function, I would assume it needs to be thread-safe because there is no way for the caller to make it thread-safe against the underlying mechanisms this function is waiting on. Like should it not be called at the same time as publish... or ... I don't even know.

The decision on whether or not to make this thread-safe is as important for the rmw implementation as it is for the caller. If we mark it thread-safe, then they have to makes sure the DDS interface (in the case of DDS) they are using is thread-safe and if not they have to make it thread-safe somehow.

2021-04-06 06:33 UTC, Barry-Xu-2018 commented
After checking some DDS implementations, I think DDS interface should be thread-safe.  
So I change the description of Thread-Safe.

2021-04-06 17:38 UTC, ivanpauno requested changes
Sorry, we're past the feature freeze so we're not going to be able to merge this.

Holding it until the `Galactic` release.

2021-04-16 09:29 UTC, Barry-Xu-2018 commented
Do rebase.

2021-05-28 20:37 UTC, ivanpauno approved these changes
LGTM!

2021-05-28 20:39 UTC, ivanpauno commented
@Barry-Xu-2018 @fujitatomoya can you run CI, including all the rmw* PRs related to this feature?
Please address the comments in https://github.com/ros2/rmw_connextdds/pull/20 first.

My plan is to get these PRs in first, and then move forward with rcl, rcl* PRs.

2021-05-30 00:44 UTC, fujitatomoya commented
@ivanpauno thanks for the effort, really appreciate it.

> can you run CI, including all the rmw* PRs related to this feature?

sounds good, we will run CI with rmw_* changes at 1st.

2021-05-30 00:48 UTC, Barry-Xu-2018 commented
@ivanpauno 

> can you run CI, including all the rmw* PRs related to this feature?
> Please address the comments in ros2/rmw_connextdds#20 first

Okay.  Thanks.

2021-05-30 02:12 UTC, fujitatomoya commented
@Barry-Xu-2018 

once you addressed https://github.com/ros2/rmw_connextdds/pull/20, could you let me know? i will create the repo file and start CI for rmw_* changes.

2021-05-30 02:44 UTC, Barry-Xu-2018 commented
> once you addressed https://github.com/ros2/rmw_connextdds/pull/20, could you let me know? i will create the repo file and start CI for rmw_* changes.

Okay，thanks.

2021-05-30 06:11 UTC, Barry-Xu-2018 commented
Do rebase.

2021-06-02 01:50 UTC, Barry-Xu-2018 commented
@fujitatomoya 

All changes for rmw* are all approved.   
Please help to create the repo file and start CI.  

Except this PR, it includes below 
- rmw_fastrtps
ros2/rmw_fastrtps#519
- rmw_connextdds
ros2/rmw_connextdds#20
- rmw_cyclonedds
ros2/rmw_cyclonedds#294
- rmw_implementation
ros2/rmw_implementation#188

2021-06-02 05:01 UTC, fujitatomoya commented
CI: (for rmw related repositories)
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14711)](http://ci.ros2.org/job/ci_linux/14711/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9463)](http://ci.ros2.org/job/ci_linux-aarch64/9463/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12376)](http://ci.ros2.org/job/ci_osx/12376/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14856)](http://ci.ros2.org/job/ci_windows/14856/)

2021-06-02 09:24 UTC, Barry-Xu-2018 commented
> macOS Build Status is failing

After checking the log, the cause seems to remote connection problem.   
I have no idea to resolve this. Maybe we should re-execute it.  
```
13:59:18 ]0;colcon build [238/308 done] [3 ongoing]Starting >>> image_transport
13:59:18 ]0;colcon build [238/308 done] [4 ongoing][Processing: image_transport, rclcpp_lifecycle, rosbag2_cpp, tf2_ros]
13:59:48 FATAL: command execution failed
14:07:20 java.nio.channels.ClosedChannelException
14:07:20 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
14:07:20 	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:221)
14:07:20 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:817)
14:07:20 	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:288)
14:07:20 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:179)
14:07:20 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:281)
14:07:20 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:501)
14:07:20 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:246)
14:07:20 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:198)
14:07:20 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:211)
14:07:20 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:785)
14:07:20 	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:172)
14:07:20 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:311)
14:07:20 	at hudson.remoting.Channel.close(Channel.java:1502)
14:07:20 	at hudson.remoting.Channel.close(Channel.java:1455)
14:07:20 	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:884)
14:07:20 	at hudson.slaves.SlaveComputer.access$100(SlaveComputer.java:110)
14:07:20 	at hudson.slaves.SlaveComputer$2.run(SlaveComputer.java:765)
14:07:20 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
14:07:20 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
14:07:20 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
14:07:20 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:07:20 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:07:20 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:07:20 	at java.lang.Thread.run(Thread.java:748)
14:07:20 Caused: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@52f33c80:JNLP4-connect connection from 70-35-50-58.static.wiline.com/70.35.50.58:62051": Remote call on JNLP4-connect connection from 70-35-50-58.static.wiline.com/70.35.50.58:62051 failed. The channel is closing down or has closed down
```

2021-06-02 11:56 UTC, fujitatomoya commented
CI (macOS):
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12378)](http://ci.ros2.org/job/ci_osx/12378/)

2021-06-02 11:56 UTC, fujitatomoya commented
@Barry-Xu-2018 i just restarted the CI for macOS.

2021-06-02 17:16 UTC, merged

2021-06-02 22:26 UTC, fujitatomoya commented
@ivanpauno appreciate for the help, thanks 👍

2021-06-03 01:08 UTC, Barry-Xu-2018 commented
@fujitatomoya @ivanpauno 

Thank you.