Add declaration for function to check QoS profile compatibility
ros2/rmw pull request #299
Opened 2021-02-11 01:58 UTC by jacobperron

Currently, users who are creating a publisher or subscription can receive 'QoS incompatibility'
events from the RMW if an incompatible endpoint is discovered. While this is useful, we
currently don't have a nice way for application to generally check if two QoS profiles are
compatible. For example, it would be nice if tooling could query the communication graph and
report any detected QoS incompatibilities.

In order to reduce code duplication, I think an API for checking QoS compatibilty should live
in a common place. I've opted for `rmw` (over a place like `rcl`) since it's possible QoS
compatiblity rules may vary per RMW vendor. Since rules for all DDS implementations should be
the same, we could put that common logic in `rmw_dds_common`.

---

Opening as a draft PR to get feedback before proceeding with an implementation.

The motivation for this API is to add features to tooling like [rqt_graph](https://github.com/ros-visualization/rqt_graph) and [ros2doctor](https://github.com/ros2/ros2cli/tree/f3a15e4b8f71336c03e56bbbf954ea87097459a0/ros2doctor) to help diagnose QoS compatibility issues. E.g. it would be useful to change how incompatible links in the ROS graph are rendered in `rqt_graph`.

2021-02-11 18:36 UTC, mjeronimo commented on rmw/include/rmw/qos_profiles.h
> + * Thread-Safe        | No
This function would definitely be handy. About the attribute table: why wouldn't this function be thread-safe and lock-free? Wouldn't it just access the two structures, evaluating for compatibility?

2021-02-11 19:32 UTC, gbiggs commented on rmw/include/rmw/qos_profiles.h
> + * \return `true` if the publisher and subscription profiles are compatible, `false` otherwise.
Do you think it would be possible to have this function or another function give an explanation of where the incompatibility is?

2021-02-17 00:44 UTC, jacobperron commented on rmw/include/rmw/qos_profiles.h
> + * Thread-Safe        | No
Yeah, I think you're right. The table can likely be updated to indicate it *is* thread-safe and lock-free.

2021-02-17 00:47 UTC, jacobperron commented on rmw/include/rmw/qos_profiles.h
> + * \return `true` if the publisher and subscription profiles are compatible, `false` otherwise.
Sure, we could add a `char **` parameter for output that can be set in the case that profiles are incompatible. This will also require we pass in an allocator for the string. It might make using the function a little more complex to use, but probably worth it for the additional information.

2021-02-17 01:49 UTC, jacobperron commented on rmw/include/rmw/qos_profiles.h
> + * \return `true` if the publisher and subscription profiles are compatible, `false` otherwise.
After talking with @wjwwood, I like the idea of avoiding an allocator completely and making this a fixed size string (e.g. 1024 characters). It's more amenable for real-time systems and makes the implementation easier.

2021-02-17 03:10 UTC, jacobperron commented
I've refactored the proposed API. Two major changes:

1. Now instead of a `bool`, it outputs the compatibility result as an enum type parameter. The return code is reserved for other errors not related to compatibility.
The compatibility can have one of three states:
    - "OK": the profiles are compatible
    - "WARNING": because one or more policies was set to "system default", we don't actually know if the profiles are compatible.
    - "ERROR": the profiles are incompatible.

2. Added a string buffer (and size) parameter for setting the reason for an incompatibility or warning.
The user should provide a pre-allocated array so that memory management is completely in their hands.

@mjeronimo @gbiggs PTAL

2021-02-17 03:11 UTC, jacobperron commented
Oh, and I also renamed the function on a whim.

2021-02-17 03:12 UTC, jacobperron commented on rmw/include/rmw/qos_profiles.h
> + * Thread-Safe        | No
Updated in 219217a

2021-02-17 03:56 UTC, mjeronimo commented
I agree with the name change given the change in the return type. 

Looks good to me, although I would've preferred a definitive yes/no answer, which would, of course, require a way to query the underlying implementation for its QoS system defaults.

2021-02-17 04:04 UTC, mjeronimo commented on rmw/include/rmw/qos_profiles.h
> +  char * reason,
I assume that the reason string would return info only about the first incompatibility encountered, correct? That is, the incompatibility check will stop upon the first incompatibility encountered and return info about that? What if there is a warning encountered first and then a compatibility error? Will the reason string provide information about the warning or the error? I'm assuming it's about the error.

2021-02-17 06:05 UTC, gbiggs commented on rmw/include/rmw/qos_profiles.h
> +  char * reason,
The first error should be given, and then the first warning if no errors. This needs to be documented.

2021-02-17 06:05 UTC, gbiggs commented on rmw/include/rmw/qos_profiles.h
> + * and `reason` is populated
```suggestion
 * and `reason` is populated.
```

2021-02-17 06:05 UTC, gbiggs commented on rmw/include/rmw/qos_profiles.h
> + * and `reason` is populated
There needs to be documentation about whether `reason` is populated in case of `ERROR` as well.

2021-02-17 06:06 UTC, gbiggs commented on rmw/include/rmw/qos_profiles.h
> + * Profile policies must not have the value "unknown". An "unknown" value is considered an error
Should this also produce a value in `reason`?

2021-02-17 06:06 UTC, gbiggs commented on rmw/include/rmw/qos_profiles.h
> + *   Must be pre-allocated by the caller. This parameter is optional and may be set to `NULL`.
```suggestion
 *   Must be pre-allocated by the caller. This parameter is optional and may be set to `nullptr`.
```

2021-02-17 06:07 UTC, gbiggs requested changes
Some documentation improvements are needed.

2021-02-17 18:45 UTC, jacobperron commented on rmw/include/rmw/qos_profiles.h
> +  char * reason,
Technically, it is possible to string together all warnings/errors. E.g. each warning/error separating by a semi-colon.

If you think it's better to return a the first error or warning, it's an easy change to make.

2021-02-17 18:48 UTC, jacobperron commented on rmw/include/rmw/qos_profiles.h
> + *   Must be pre-allocated by the caller. This parameter is optional and may be set to `NULL`.
This is a C API; `nullptr` is not defined as it is a C++11 thing.

2021-02-17 20:31 UTC, wjwwood commented
> Added a string buffer (and size) parameter for setting the reason for an incompatibility or warning.
The user should provide a pre-allocated array so that memory management is completely in their hands.

👍 like this even more than what we talked about.

2021-02-17 23:51 UTC, gbiggs commented on rmw/include/rmw/qos_profiles.h
> +  char * reason,
The problem with stringing them all together is that the user might pass in a buffer that's only big enough to hold one, which might happen to be a warning. I guess that could be documented, though.

2021-02-17 23:52 UTC, gbiggs commented on rmw/include/rmw/qos_profiles.h
> + *   Must be pre-allocated by the caller. This parameter is optional and may be set to `NULL`.
Oh, I thought `nullptr` made it into the latest C as well. What a shame.

2021-02-18 01:36 UTC, jacobperron commented on rmw/include/rmw/qos_profiles.h
> +  char * reason,
Yeah, it's a problem in general that `reason` may not be large enough even for a single error/warning.
For the DDS implementations, I can make sure that errors appear before warnings.

2021-02-18 05:27 UTC, jacobperron commented
I've opened a PR with the implementation for DDS RMWs here: https://github.com/ros2/rmw_dds_common/pull/45

2021-02-18 05:27 UTC, jacobperron commented on rmw/include/rmw/qos_profiles.h
> + * Profile policies must not have the value "unknown". An "unknown" value is considered an error
Yeah, I think that makes sense. Documented in 28a9f5f.

2021-02-18 05:27 UTC, jacobperron commented on rmw/include/rmw/qos_profiles.h
> + * and `reason` is populated
See 28a9f5f

2021-02-18 05:28 UTC, jacobperron commented on rmw/include/rmw/qos_profiles.h
> + * and `reason` is populated
Fixed in 28a9f5f

2021-02-18 05:28 UTC, jacobperron commented on rmw/include/rmw/qos_profiles.h
> +  char * reason,
Documented in 28a9f5f

2021-02-18 22:53 UTC, jacobperron commented on rmw/include/rmw/qos_profiles.h
> + * and `reason` is populated
Changed my mind after doing the implementation. If there is an error code result, then no output parameters will be set: 041f02c

2021-02-19 20:06 UTC, jacobperron commented
Thanks for the feedback! I've updated this PR and opened a bunch of connected PRs that implement this for our supported RMWs (see the updated description for a list). The common implementation lives in `rmw_dds_common`, so this one could use the most scrutiny: ros2/rmw_dds_common#45

2021-02-20 01:03 UTC, mjeronimo commented on rmw/include/rmw/qos_profiles.h
> + *   This parameter is optional and may be set to `NULL` if the reason information is not
Use 'nullptr's here instead of NULLs?

2021-02-22 13:13 UTC, ivanpauno commented on rmw/include/rmw/qos_profiles.h
> + *   This parameter is optional and may be set to `NULL` if the reason information is not
`nullptr` is cpp only AFAIK

2021-02-22 13:16 UTC, ivanpauno approved these changes

2021-02-22 13:17 UTC, ivanpauno commented on rmw/include/rmw/qos_profiles.h
> + * `compatibility` and `reason` will not be set.
Pending discussion in another PR https://github.com/ros2/rmw_dds_common/pull/45#discussion_r580215422

2021-02-23 01:49 UTC, jacobperron commented on rmw/include/rmw/qos_profiles.h
> + * `compatibility` and `reason` will not be set.
Updated 93e9aa2

Unknown values now result in a compatibility warning instead of an error.

2021-02-23 13:23 UTC, ivanpauno approved these changes

2021-02-24 06:40 UTC, fujitatomoya approved these changes
lgtm

2021-02-24 19:31 UTC, jacobperron commented
Thanks for all the feedback so far!

I'm just waiting for ci.ros2.org to come back online and then I'll trigger CI and get this merged/released.

2021-02-25 19:14 UTC, merged

2021-03-05 21:16 UTC, asorbini commented
I noticed this new API from a new test failure in `test_rmw_implementation`, and added support for it to `rmw_connextdds` in [91753dc](https://github.com/rticommunity/rmw_connextdds/commit/91753dcc9ad7dc7c21d77eda0684ff646ad5994b).

I also noticed that these changes have not yet made it to the Rolling Debian binaries, and I had to build the tree from source in order to validate them. What is the period with which those packages are usually regenerated?

2021-03-08 14:07 UTC, ivanpauno commented
I think that releasing `rmw_implementation` is pending, but IIUC @jacobperron already released up to `rmw`.

> I also noticed that these changes have not yet made it to the Rolling Debian binaries, and I had to build the tree from source in order to validate them. What is the period with which those packages are usually regenerated?

IIUC the packages used by `build.ros2.org` for testing will be updated almost right away (delay of some hours), but the public ones (the ones you download when `apt install ...`) will only get updated after a sync.
I guess there will be a sync in about May as ROS 2 Galactic will be released for that date, though IDK.

2021-03-08 17:45 UTC, jacobperron commented
@ivanpauno is correct. If you switch to the testing repo ([see instructions](https://docs.ros.org/en/foxy/Installation/Prerelease-Testing.html#debian-testing-repository)), then you should see these changes already released there. Syncs to main happen periodically (roughly every three weeks), though I don't think there has been one for a couple months now.

@nuclearsandwich what do you think about doing a Rolling sync in the near future?