Improve handling of dynamic discovery - rmw changes
ros2/rmw pull request #338
Opened 2022-12-14 07:14 UTC by gbiggs

This PR adds to `rmw` functionality necessary to support the [improved handling of dynamic discovery].

It adds handling of the new discovery-related configuration parameters to `rmw` so they can be used by `rcl` to control the behaviour of RMW implementations.

2022-12-14 14:02 UTC, ivanpauno reviewed
LGTM!

I have some minor comments/suggestions.

2022-12-14 14:02 UTC, ivanpauno commented on rmw/include/rmw/discovery_params.h
> +#define RMW_DISCOVERY_PARAMS_MAX_PEERS 32
is there a limit in DDS vendors?

2022-12-14 22:27 UTC, methylDragon commented on rmw/include/rmw/discovery_params.h
> +  char static_peers[RMW_DISCOVERY_PARAMS_MAX_PEERS][RMW_DISCOVERY_PARAMS_PEER_MAX_LENGTH];
If there's no reason that the `RMW_DISCOVERY_PARAMS_MAX_PEERS` should be capped at 32, we should either have that "32" be a passed in cmake arg, an environment variable, or otherwise go with a dynamic array:

```
peer_address_t * static_peers;
```

And then take in a size argument in the `rmw_get_zero_initialized_discovery_params` below.

2022-12-15 14:42 UTC, ivanpauno commented on rmw/include/rmw/discovery_params.h
> +  char static_peers[RMW_DISCOVERY_PARAMS_MAX_PEERS][RMW_DISCOVERY_PARAMS_PEER_MAX_LENGTH];
> There is the open question about what to do for people who want to pre-allocate everything, but this isn't the only place they'll have to deal with that.

IIUC, this would only be allocated once from the environment variables when you create the node, so it shouldn't be an issue.

2023-02-02 00:15 UTC, fujitatomoya commented on rmw/include/rmw/discovery_params.h
> +  RMW_AUTOMATIC_DISCOVERY_RANGE_SUBNET = 3,
What if system has multiple network interface? that is also rmw implementation dependent as it is now?

2023-02-02 00:15 UTC, fujitatomoya commented on rmw/src/discovery_params.c
> +        RMW_DISCOVERY_PARAMS_PEER_MAX_LENGTH) != 0)
What about the one is with hostname which can be DNSed to IP, and the other with the same IP address? that is not supported here?

2023-02-21 22:29 UTC, ros-discourse commented
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2023-02-16/29927/1

2023-03-24 23:14 UTC, sloretz commented
@arjo129 can this be closed now that #349 merged?

2023-03-27 05:05 UTC, wjwwood commented on rmw/include/rmw/discovery_params.h
> +  char static_peers[RMW_DISCOVERY_PARAMS_MAX_PEERS][RMW_DISCOVERY_PARAMS_PEER_MAX_LENGTH];
`static_peers` is dynamic now.

2023-03-27 05:23 UTC, wjwwood reviewed
API and functions that are implemented here lgtm, but we should have some tests for those new functions that live here. I think @sloretz and I can help with that tomorrow.

2023-03-27 05:23 UTC, wjwwood commented on rmw/include/rmw/discovery_options.h
> +/// Used to enable or disable the use of multicast for node discovery
I think we should reword the docstrings to avoid mentioning multicast. This should affect discovery range even if multicast is not used by the underlying middleware, in my opinion.

2023-03-27 05:23 UTC, wjwwood commented on rmw/include/rmw/discovery_options.h
> +/// Used to specify the parameters that control how discovery is performed
```suggestion
/// Used to specify the options that control how discovery is performed
```

2023-03-27 05:23 UTC, wjwwood commented on rmw/include/rmw/discovery_options.h
> +/// Perform a deep copy of the discovery parameters from src into dst using the
```suggestion
/// Perform a deep copy of the discovery options from src into dst using the
```

2023-03-27 05:23 UTC, wjwwood commented on rmw/include/rmw/discovery_options.h
> + * \return RMW_RET_BAD_ALLOC if allocation fails.
```suggestion
 * The dst will be left with an owned copy of the static peers
 * array whose string values match the src.
 * If successful, src and dst will evaluate as equal using
 * rmw_discovery_options_equal.
 *
 * \param[in] src discovery option parameters to be copied.
 * \param[in] allocator to use.
 * \param[out] dst Destination parameters to use.
 * \return RMW_RET_OK if success.
 * \return RMW_RET_INVALID_ARGUMENT if either the src, allocator or dst is null.
 * \return RMW_RET_BAD_ALLOC if allocation fails.
```

2023-03-27 05:25 UTC, wjwwood commented
I also think we need to address @fujitatomoya's comments, as I think they're still relevant even after the changes.

2023-03-27 06:40 UTC, arjo129 commented on rmw/include/rmw/discovery_params.h
> +  RMW_AUTOMATIC_DISCOVERY_RANGE_SUBNET = 3,
Yes. That is out of scope of this PR.

2023-03-27 06:49 UTC, arjo129 commented
I don't have push access to this repo. Would you like me to open yet another PR?

2023-03-27 12:26 UTC, clalancette commented
> I don't have push access to this repo. Would you like me to open yet another PR?

@arjo129 I invited you to have push access.  Once you accept, you should be able to continue here.

2023-03-27 21:25 UTC, sloretz commented on rmw/include/rmw/discovery_options.h
> +/// Used to enable or disable the use of multicast for node discovery
Reworded to avoid mentioning multicast in 9e72cec

2023-03-27 21:25 UTC, sloretz commented on rmw/include/rmw/discovery_options.h
> +/// Used to specify the parameters that control how discovery is performed
`parameters` -> `options` in 91beb13

2023-03-27 21:25 UTC, sloretz commented on rmw/include/rmw/discovery_options.h
> +/// Perform a deep copy of the discovery parameters from src into dst using the
`parameters` -> `options` in 91beb13

2023-03-27 21:25 UTC, sloretz commented on rmw/include/rmw/discovery_options.h
> + * \return RMW_RET_BAD_ALLOC if allocation fails.
one sentence per line in 5fc6ce9

2023-03-27 21:34 UTC, sloretz commented on rmw/include/rmw/discovery_params.h
> +  RMW_AUTOMATIC_DISCOVERY_RANGE_DEFAULT = 0,
The QoS enums have a [*_SYSTEM_DEFAULT value](https://github.com/ros2/rmw/blob/866bc299f5278c91c107353a907d5e971d2e8e24/rmw/include/rmw/qos_profiles.h#L33). I forget what this was for. Was it to allow setting QoS via a middleware specific configuration?

If so,  `RMW_AUTOMATIC_DISCOVERY_RANGE_SYSTEM_DEFAULT` might be useful to say "don't mess with discovery settings, they're already configured with middleware specific APIs".

2023-03-27 23:57 UTC, sloretz commented
@wjwwood FYI 2cf62e35a3536bfa5bed74f54ca829511010c657 is a sizeable change. It:

* adds `rmw_discovery_options_init()` to allocation options with a set number of static peers
* adds an allocator member to the `rmw_discovery_options_t` object
* uses a pointer to an allocator as an argument [because I saw that used elsewhere](https://github.com/ros2/rmw/blob/866bc299f5278c91c107353a907d5e971d2e8e24/rmw/include/rmw/get_topic_names_and_types.h#L95)
* errors if `copy` is called with same object for src and dst
* adds a whole bunch of tests

2023-03-28 00:38 UTC, wjwwood requested changes
one small necessary (imo) change, otherwise lgtm

2023-03-28 00:38 UTC, wjwwood commented on rmw/include/rmw/discovery_options.h
> +  const rcutils_allocator_t * allocator,
We're inconsistent on this, but I think this should be non-const. This doesn't actually do anything, because it's like saying `const int ...`, since the `const` here only says we're not going to change the value of the pointer, not that the thing being pointed to is `const`.

2023-03-28 00:38 UTC, wjwwood commented on rmw/include/rmw/discovery_options.h
> +  const rcutils_allocator_t * allocator,
Also, the allocator's state (conceptually) is changing when this is called. So I think it's also more correct to say it should be non-const.

2023-03-28 00:38 UTC, wjwwood commented on rmw/src/discovery_options.c
> +    return RMW_RET_INVALID_ARGUMENT;
Is this case documented in the docstring?

2023-03-28 00:49 UTC, sloretz commented on rmw/include/rmw/discovery_options.h
> +  const rcutils_allocator_t * allocator,
That makes sense. Changed back to non-const in 8258369b13058e7dc59993eec655cfa76b9c1d44

2023-03-28 00:49 UTC, sloretz commented on rmw/src/discovery_options.c
> +    return RMW_RET_INVALID_ARGUMENT;
Documented this case in 6086e681e33637580f13cb37589de187bc5e8d1a

2023-03-28 00:59 UTC, wjwwood approved these changes

2023-03-28 02:34 UTC, mxgrey commented on rmw/include/rmw/discovery_options.h
> +  const rcutils_allocator_t * allocator,
> This doesn't actually do anything

I apologize for the bikeshedding I'm about to do, but I don't think it's accurate to say it's the same as `const int ...`. The `const` in this case says we're not going to change **the values of any fields in the struct that you are giving us a reference to**. E.g.

```
typedef struct MyData_s {
  int my_num;
} MyData_t;

void can_change_field_value(MyData_t * data) {
  data->my_num += 1;
}

void cannot_change_field_value(const MyData_t * data) {
  data->my_num += 1; // fails to compile
}
```

> says we're not going to change the value of the pointer

The syntax for that would be `rcutils_allocator_t * const allocator`. That indeed would give an equivalent function signature to `rcutils_allocator_t * allocator`.

> allocator's state (conceptually) is changing when this is called

I already shared some thoughts on logical vs physical const and the principle of least mutability [back in this comment](https://github.com/ros2/rmw/pull/349#discussion_r1130398836) so I won't rehash that. It's mostly inconsequential here because I suppose no one downstream is going to care much about having an immutable allocator, but more broadly I think C/C++'s relationship with mutability is a perilous one, being mutable by default, so developers have a responsibility to make generous use of `const` wherever applicable. This discussion isn't worth holding up this PR, but I think it's an issue worth being mindful of more generally.

2023-03-28 19:40 UTC, wjwwood commented on rmw/include/rmw/discovery_params.h
> +  RMW_AUTOMATIC_DISCOVERY_RANGE_DEFAULT = 0,
That's right @sloretz.

I think @mxgrey is also right, it's weird if we're never sending the value down to rmw, so we should either not have it as an rmw option or we should handle it in the rmw layer. It might make sense to have ROS/RCL version that has system default but not have one in RMW if that one doesn't make sense. I know we only have RMW enums atm, however.

However, it might just be that we shouldn't be automatically be converting the DEFAULT into LOCALHOST as we are now.

2023-03-28 19:52 UTC, sloretz commented on rmw/include/rmw/discovery_params.h
> +  RMW_AUTOMATIC_DISCOVERY_RANGE_DEFAULT = 0,
> However, it might just be that we shouldn't be automatically be converting the `DEFAULT` into `LOCALHOST` as we are now.

If we are just converting `DEFAULT` to `LOCALHOST` ( I see that happening in the rmw_cyclonedds_cpp PR) then I agree it doesn't seem like an option at the RMW layer is necessary.

If someone wants to use an XML config, and doesn't want the `rmw_*` layer to mess with discovery settings, and the default discovery range is localhost,  what option should they provide for the range? `SUBNET` since [the default behavior seems to be to do nothing, at least for cyclonedds](https://github.com/ros2/rmw_cyclonedds/pull/429/files#diff-91f31a99b38624440900850fd2df4710f2ef46c140999f3e3b8b89393e48e202R1075-R1078)?

2023-04-07 00:29 UTC, wjwwood approved these changes

2023-04-08 04:35 UTC, merged