Runtime Interface Reflection: rmw
ros2/rmw pull request #340
Opened 2023-01-03 23:53 UTC by methylDragon

Includes changes to the RMW APIs for supporting runtime interface reflection

2023-04-06 03:20 UTC, wjwwood commented on rmw/CMakeLists.txt
> +find_package(rosidl_dynamic_typesupport REQUIRED)
move below with other deps

2023-04-06 03:21 UTC, wjwwood commented on rmw/CMakeLists.txt
> +ament_export_dependencies(rosidl_dynamic_typesupport)
move up with other export deps

2023-04-06 03:22 UTC, wjwwood commented on rmw/package.xml
>    <build_export_depend>rosidl_runtime_c</build_export_depend>
alphabetize

2023-04-06 18:13 UTC, methylDragon commented on rmw/package.xml
>    <build_export_depend>rosidl_runtime_c</build_export_depend>
https://github.com/ros2/rmw/pull/340/commits/af30f1d55cfb68fee77aeab7d5ec78c46b593648

2023-04-06 18:13 UTC, methylDragon commented on rmw/CMakeLists.txt
> +ament_export_dependencies(rosidl_dynamic_typesupport)
https://github.com/ros2/rmw/pull/340/commits/af30f1d55cfb68fee77aeab7d5ec78c46b593648

2023-04-06 18:13 UTC, methylDragon commented on rmw/CMakeLists.txt
> +find_package(rosidl_dynamic_typesupport REQUIRED)
https://github.com/ros2/rmw/pull/340/commits/af30f1d55cfb68fee77aeab7d5ec78c46b593648

2023-04-07 23:21 UTC, wjwwood requested changes
We have some interfaces to remove/move, but otherwise lgtm

2023-04-07 23:21 UTC, wjwwood commented on rmw/src/dynamic_message_type_support.c
> +}
I think this one should also be deleted, as it doesn't seem to provide any value over calling the `rosidl_dynamic_typesupport` version of this. I was going to comment that `success` doesn't necessary imply there wasn't enough memory, or if it does, then that should just be a different return code, but I think we just remove this entirely from `rmw`.

2023-04-07 23:21 UTC, wjwwood commented on rmw/src/dynamic_message_type_support.c
> +}
Same for this one, probably should just remove it.

2023-04-07 23:21 UTC, wjwwood commented on rmw/src/dynamic_message_type_support.c
> +}
Also, I think we should move this function to `rosidl_dynamic_typesupport`.

2023-04-08 01:10 UTC, methylDragon commented on rmw/src/dynamic_message_type_support.c
> +}
Moved! (See rosidl_dynamic_typesupport PR https://github.com/ros2/rosidl_dynamic_typesupport/pull/1)

2023-04-08 01:10 UTC, methylDragon commented on rmw/src/dynamic_message_type_support.c
> +}
https://github.com/ros2/rmw/pull/340/commits/4de8ad65e91bc088af0a4a456e9a179bc348f5bb

2023-04-08 01:10 UTC, methylDragon commented on rmw/src/dynamic_message_type_support.c
> +}
https://github.com/ros2/rmw/pull/340/commits/4de8ad65e91bc088af0a4a456e9a179bc348f5bb

2023-04-08 01:10 UTC, methylDragon commented on rmw/include/rmw/dynamic_message_type_support.h
> +  rosidl_dynamic_typesupport_dynamic_data_t ** cloned_dynamic_message);  // OUT
https://github.com/ros2/rmw/pull/340/commits/4de8ad65e91bc088af0a4a456e9a179bc348f5bb

2023-04-08 09:13 UTC, wjwwood approved these changes

2023-04-08 19:02 UTC, merged