Add field topic_type_hash to rmw_topic_endpoint_info_t
ros2/rmw pull request #348
Opened 2023-02-14 23:01 UTC by emersonknapp

2023-03-13 06:43 UTC, emersonknapp commented
@wjwwood @methylDragon @ivanpauno this is ready for review, the types are finalized in the dependency PR, we're only hashing out final details

2023-03-13 18:40 UTC, clalancette requested changes
One minor thing to fix here, then I think this is good to go.

2023-03-13 18:40 UTC, clalancette commented on rmw/include/rmw/topic_endpoint_info.h
> + * This functions copies value `topic_type_hash` into data structure `topic_type_hash` member.
```suggestion
 * This function copies value `topic_type_hash` into data structure `topic_type_hash` member.
```

But actually, I don't actually understand what this is trying to tell me.  I guess it copies the data from the given `rosidl_type_hash_t` structure into the `rmw_topic_endpoint_info_t` structure member, correct?  It might be better to rewrite this sentence to say that.

2023-03-13 20:13 UTC, emersonknapp commented on rmw/include/rmw/topic_endpoint_info.h
> + * This functions copies value `topic_type_hash` into data structure `topic_type_hash` member.
Yeah sorry, copypasta result, I hadn't read it too closely, just changed out the names. I've done a pass to clean up the language on all the docstrings in this file.

2023-03-13 20:29 UTC, clalancette approved these changes
Looks good to me with green CI.

2023-03-15 14:29 UTC, clalancette commented
I had to rebase this to get the incompatible type stuff in.  I've done that now, here is another CI:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18237)](http://ci.ros2.org/job/ci_linux/18237/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12768)](http://ci.ros2.org/job/ci_linux-aarch64/12768/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18909)](http://ci.ros2.org/job/ci_windows/18909/)

2023-03-15 19:36 UTC, clalancette commented
The test failures on Windows are known flakes.  So going ahead and merging this one in.

2023-03-15 19:37 UTC, merged