Improve handling of dynamic discovery - rmw changes (Extends #338)
ros2/rmw pull request #349
Opened 2023-03-02 07:20 UTC by arjo129

This PR extends #338 to support dynamic memory allocation.

2023-03-07 07:57 UTC, wjwwood requested changes
A few style and implementation questions, as well as some naming considerations, but otherwise looks reasonable to me.

One thing I'm unsure about still, and I'm sure I'll see this elsewhere, is how the static peers are managed? Seems like there should be functions to help modify that array within the discovery params, in order to help avoid mistakes. Similar to how we have helpers for using the array types in rcutils:

https://github.com/ros2/rcutils/blob/rolling/include/rcutils/types/char_array.h#L106-L240

I don't think we need all of those, but some functions to help with resizing and adding/removing would be good I think.

2023-03-07 07:57 UTC, wjwwood commented on rmw/include/rmw/discovery_params.h
> +  peer_address_t* static_peers;
I think the style checks will catch this, but I think it will be:

```suggestion
  peer_address_t * static_peers;
```

2023-03-07 07:57 UTC, wjwwood commented on rmw/include/rmw/discovery_params.h
> +rmw_discovery_params_equal(rmw_discovery_params_t * left, rmw_discovery_params_t * right);
What is the behavior of this function if either of the pointers are nullptr? I think it would be useful to document the expectations, and potentially we may need a return code with an "out" parameter for the comparison result. Similarly since the struct contains an array, what is the behavior when one of the two have invalid arrays (nullptr to array head)?

2023-03-07 07:57 UTC, wjwwood commented on rmw/include/rmw/discovery_params.h
> +} rmw_discovery_params_t;
nitpick: we should use full names and avoid abbreviations for the benefit of folks who are translating this from English to something else, e.g. `rmw_discovery_parameters_t`.

2023-03-07 07:57 UTC, wjwwood commented on rmw/include/rmw/discovery_params.h
> +  rmw_discovery_params_t * dst);
What is the behavior of this function? I assume it copies the array of static peers, using the allocator, but we should have it detail the things it will do during the copy.

2023-03-07 07:57 UTC, wjwwood commented on rmw/include/rmw/discovery_params.h
> +  const rcutils_allocator_t * allocator);
In other places in the API we prefer to store the allocator in the data structure so that you don't need to pass it in the fini function, making it more or less impossible to accidentally pass the wrong allocator here. This has the disadvantage of making the data structure larger (by the size  of the allocator) but the advantage that the above issue I described and so that you don't have to check the allocator pointer here (might be nullptr).

2023-03-07 07:57 UTC, wjwwood commented on rmw/include/rmw/discovery_params.h
> +  const rcutils_allocator_t * allocator,
I think we sometimes pass the allocator as a pointer and other times as a value, which is unfortunately inconsistent of us, but my guiding rule is that if you will definitely use the allocator, e.g. ensured allocations will happen or you'll store the allocator in the data structure as part of init, then passing as a value is nice, so you don't have to validate the pointer to the allocator.

2023-03-07 07:57 UTC, wjwwood commented on rmw/include/rmw/discovery_params.h
> +  const rcutils_allocator_t * allocator);
Also, not sure the allocator being const here makes sense. There's a philosophical debate about deep const-ness and expectation signaling, but in this case my expectation is that the conceptual "state" of the allocator will change when something is fini'ed (or may change) and therefore probably shouldn't be const, even though we're technically not changing any shallow values in the allocator struct itself.

2023-03-07 07:57 UTC, wjwwood commented on rmw/include/rmw/impl/cpp/key_value.hpp
> +parse_key_value(const std::vector<uint8_t>& kv)
```suggestion
parse_key_value(const std::vector<uint8_t> & kv)
```

2023-03-07 07:57 UTC, wjwwood commented on rmw/include/rmw/discovery_params.h
> +} rmw_discovery_params_t;
Same goes for the file name, `discovery_parameters.h` and related files too.

2023-03-07 07:57 UTC, wjwwood commented on rmw/include/rmw/discovery_params.h
> +#define RMW_DISCOVERY_PARAMS_PEER_MAX_LENGTH 256
nitpick: use full name, e.g. `RMW_DISCOVERY_PARAMETERS_STATIC_PEER_MAX_LENGTH`, including "static" and the full "parameters" name.

2023-03-07 07:57 UTC, wjwwood commented on rmw/include/rmw/init_options.h
> +  rmw_discovery_params_t discovery_params;
Kind of meta, but seeing it here, I'm wondering why "parameters" rather than "options"? Seems like `rmw_discovery_options_t` would be a better name. "parameters" is a kind of overloaded term in the ROS world, so avoiding it in favor of a more conventional and less overloaded term like "options" seems attractive to me.

2023-03-07 07:57 UTC, wjwwood commented on rmw/src/discovery_params.c
> +    strncpy(
This is likely to produce warnings about not using the `_s` "safe" version of the function. Especially on Windows. Just be ready for that in the CI testing.

2023-03-07 07:57 UTC, wjwwood commented on rmw/src/discovery_params.c
> +    allocator->deallocate(discovery_params->static_peers, allocator->state);
Use `{}`'s:

```suggestion
  if (discovery_params->static_peers_count > 0) {
    allocator->deallocate(discovery_params->static_peers, allocator->state);
  }
```

2023-03-07 07:57 UTC, wjwwood commented on rmw/src/discovery_params.c
> +  {
uncrustify should catch this (maybe it hasn't been run yet), but I think it should be:

```suggestion
  for (size_t i = 0; i < src->static_peers_count; i++) {
```

2023-03-07 08:04 UTC, wjwwood commented
Also we should consolidate this with https://github.com/ros2/rmw/pull/338 and address the feedback there as well.

2023-03-09 03:44 UTC, mxgrey commented on rmw/include/rmw/discovery_params.h
> +rmw_discovery_params_equal(rmw_discovery_params_t * left, rmw_discovery_params_t * right);
These changes should address your concerns: [d63987b](https://github.com/ros2/rmw/pull/349/commits/d63987bb9501f8c119d146690ccc58801adcd092)

It's now using `rmw_ret_t` as a return value with a `bool *` output parameter. Passing in a nullptr for any argument gets a `RMW_RET_INVALID_ARGUMENT` return value. If either parameter struct has a nullptr array with a non-zero static peers count, that also triggers a `RMW_RET_INVALID_ARGUMENT`.

2023-03-09 03:52 UTC, mxgrey commented on rmw/include/rmw/discovery_params.h
> +} rmw_discovery_params_t;
Names have been updated, including changing `peer_address` to `rmw_peer_address`: [62d0aba](https://github.com/ros2/rmw/pull/349/commits/62d0aba8b438e59e7e690d54403198c6ec6859f3)

2023-03-09 04:01 UTC, mxgrey commented on rmw/include/rmw/discovery_params.h
> +  rmw_discovery_params_t * dst);
Documentation updated: [3850bc3](https://github.com/ros2/rmw/pull/349/commits/3850bc3b3893ddd04778e278ae685c341db2a384)

2023-03-09 04:03 UTC, mxgrey commented on rmw/include/rmw/discovery_params.h
> +  const rcutils_allocator_t * allocator);
> In other places in the API we prefer to store the allocator in the data structure

Based on downstream usage of this API in the various RMW implementations, I don't think there's any value in storing the allocator in the struct. All the different RMW implementations which are handling the `rmw_discovery_parameters` struct already have an allocator stored which they can use for this.

2023-03-09 04:15 UTC, mxgrey commented on rmw/include/rmw/discovery_params.h
> +} rmw_discovery_params_t;
Also some more `params` -> `parameters`: [d96be10](https://github.com/ros2/rmw/pull/349/commits/d96be103a67cfeead6fbadec02a6c7b02ac90b3c)

2023-03-09 04:20 UTC, mxgrey commented on rmw/include/rmw/discovery_params.h
> +  const rcutils_allocator_t * allocator,
Changed to value parameter: [245d6bc](https://github.com/ros2/rmw/pull/349/commits/245d6bc8b69b0097734d5ec90c156014af6825b9)

2023-03-09 04:20 UTC, mxgrey commented on rmw/include/rmw/discovery_params.h
> +  const rcutils_allocator_t * allocator);
This concern is irrelevant now because it's being passed by value: [245d6bc](https://github.com/ros2/rmw/pull/349/commits/245d6bc8b69b0097734d5ec90c156014af6825b9)

2023-03-09 04:28 UTC, mxgrey commented on rmw/include/rmw/init_options.h
> +  rmw_discovery_params_t discovery_params;
I wish I had seen this before my earlier renaming iterations, but I agree.

[1d16081](https://github.com/ros2/rmw/pull/349/commits/1d16081bd4319b467b998460ae2d4201fb51c6d4) changes `discovery_parameters` to `discovery_options`.

2023-03-09 04:29 UTC, mxgrey commented on rmw/include/rmw/discovery_params.h
> +#define RMW_DISCOVERY_PARAMS_PEER_MAX_LENGTH 256
Taken care of in [1d16081](https://github.com/ros2/rmw/pull/349/commits/1d16081bd4319b467b998460ae2d4201fb51c6d4), plus `parameters` -> `options`.

2023-03-09 04:29 UTC, mxgrey commented on rmw/include/rmw/impl/cpp/key_value.hpp
> +parse_key_value(const std::vector<uint8_t>& kv)
Buried inside of [1d16081](https://github.com/ros2/rmw/pull/349/commits/1d16081bd4319b467b998460ae2d4201fb51c6d4)

2023-03-09 04:47 UTC, mxgrey commented on rmw/src/discovery_params.c
> +    strncpy(
It seems `strncpy_s` [was introduced in C11](https://en.cppreference.com/w/c/string/byte/strncpy) but we're currently using `C99` according to the `CMAKE_C_STANDARD` setting in the `CMakeLists.txt`.

Are we okay with bumping that to `C11`?

2023-03-09 04:49 UTC, mxgrey commented on rmw/src/discovery_params.c
> +    allocator->deallocate(discovery_params->static_peers, allocator->state);
Fixed: [1152b9b](https://github.com/ros2/rmw/pull/349/commits/1152b9b1392488e0b7c74ec9213d30df82f023d4)

2023-03-09 04:49 UTC, mxgrey commented on rmw/src/discovery_params.c
> +  {
Fixed: [1152b9b](https://github.com/ros2/rmw/pull/349/commits/1152b9b1392488e0b7c74ec9213d30df82f023d4)

2023-03-20 14:49 UTC, wjwwood commented on rmw/src/discovery_params.c
> +    strncpy(
Either way, you'll have to do some conditional logic to support Windows. This is why we sometimes use the rctuils format string functions, rather than using `strncpy`, but either way is fine.

2023-03-20 15:07 UTC, wjwwood reviewed
small style comments, but otherwise lgtm

We should really close #338 or merge this one into it.

2023-03-20 15:07 UTC, wjwwood commented on rmw/include/rmw/discovery_options.h
> +/// a nullptr while static_peers_count is non-zero.
nitpick: this doesn't match our doxygen style for the rest of the code in this package, specifically:

- new sentences start on new lines
- use of `///` only for the brief, `/**` blocks otherwise
- use of directives like `\return`

Example of a standard block:

https://github.com/ros2/rmw/blob/114e1e7ba9174b7dff8d10b82fdcb0b54ae5aff8/rmw/include/rmw/init_options.h#L74-L106

re: use one sentence per line

> - [any] Each sentence must start on a new line.
>   - Rationale: For longer paragraphs a single change in the beginning makes the diff unreadable since it carries forward through the whole paragraph.

https://docs.ros.org/en/rolling/Contributing/Code-Style-Language-Versions.html#markdown-restructured-text-docblocks

I'd reformat this one as:

```suggestion
/// Compare two discovery parameter instances for equality.
/**
 * Equality means the automatic_discovery_range values are equal,
 * they have the same static_peers_count value, and each entry in
 * static_peers is evaluated as equal using strncmp.
 *
 * NOTE: If the two parameter structs list the static peers in different orders
 * then this will evaulate as NOT equal.
 *
 * \return `RMW_RET_OK` when the input arguments are valid, or
 * \return `RMW_RET_INVALID_ARGUMENT` when any input is a nullptr, or
 *   if something in either struct was malformed, such as static_peers being
 *   a nullptr while static_peers_count is non-zero.
 */
```

2023-03-20 15:07 UTC, wjwwood commented on rmw/include/rmw/discovery_options.h
> +/// evaluate as equal using rmw_discovery_options_equal.
Same nitpick about style as the other, but also (not a nitpick) we should have documentation about the return codes that are possible and when they will occur.

2023-03-21 18:52 UTC, wjwwood commented
Aside from a conversation about strncpy, I think all my review comments were addressed. I'm going to merge this with geoff's prs and continue there.

2023-03-21 18:52 UTC, merged