Initialize the NULL strucutre with static value.
ros2/rmw pull request #378
Opened 2024-09-09 20:11 UTC by fujitatomoya

closes https://github.com/ros2/rmw/issues/377

2024-09-09 20:12 UTC, fujitatomoya commented
@comicfans could you try this patch to see if it fixes your asan warning?

2024-09-09 21:24 UTC, methylDragon commented
Makes sense to me, since the the struct is nested.

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21820)](http://ci.ros2.org/job/ci_linux/21820/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16090)](http://ci.ros2.org/job/ci_linux-aarch64/16090/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1322)](http://ci.ros2.org/job/ci_linux-rhel/1322/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22520)](http://ci.ros2.org/job/ci_windows/22520/)

2024-09-09 21:25 UTC, methylDragon approved these changes

2024-09-09 22:03 UTC, clalancette requested changes
So looking through `rmw` here, it looks like quite a few of the `get_zero_initialized` functions don't follow this pattern.  I'm thinking we should update all of them in this PR, what do you think @fujitatomoya ?

2024-09-10 00:21 UTC, fujitatomoya commented
@clalancette sounds good to me, let me try to replace them all.

2024-09-10 03:58 UTC, fujitatomoya commented on rmw/src/names_and_types.c
> -  zero.names = rcutils_get_zero_initialized_string_array();
Now i think opposite against this change.

maybe we should call `rcutils_get_zero_initialized_string_array` for both `names` and `types` to initialize those fields with allocating memory in stack? unless, once `rcutils_string_array_t` is modified, we need to update this code too.
IMO, correct way is to use stack memory and return the initialized values?

2024-09-10 04:00 UTC, fujitatomoya commented on rmw/src/names_and_types.c
> -  zero.names = rcutils_get_zero_initialized_string_array();
@methylDragon what do you think above?

2024-09-10 07:48 UTC, comicfans commented
> @comicfans could you try this patch to see if it fixes your asan warning?

confirm this fix the problem

2024-09-11 23:09 UTC, fujitatomoya reviewed
@methylDragon @clalancette what do you think? could you take a look when you have time?

2024-09-11 23:09 UTC, fujitatomoya commented on rmw/src/discovery_options.c
> +  static const rmw_discovery_options_t result = {
use `static const` to have this in the code read-only segment so that we can use code cache and avoid runtime memory allocation.

2024-09-11 23:09 UTC, fujitatomoya commented on rmw/src/event.c
> +  /// We should introduce xxx_get_default_event to return the default values.
some xxx_get_zero_initialized_yyy functions have default values which are not zero initialized. i think what we need to do here is to call zero initialized function 1st and then get the default values for the structure. i would like to process one thing at a time, so this `TODO` comment is added as follow-up item.

2024-09-12 16:44 UTC, fujitatomoya commented
@clalancette can you take a look at this?

2024-09-12 16:45 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21831)](http://ci.ros2.org/job/ci_linux/21831/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16101)](http://ci.ros2.org/job/ci_linux-aarch64/16101/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1333)](http://ci.ros2.org/job/ci_linux-rhel/1333/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22537)](http://ci.ros2.org/job/ci_windows/22537/)

2024-09-12 17:17 UTC, clalancette requested changes
One minor change, then I'm happy with this.

2024-09-12 17:17 UTC, clalancette commented on rmw/src/discovery_options.c
>      .static_peers_count = 0,
So actually, RMW_AUTOMATIC_DISCOVERY_RANGE_NOT_SET is 0, so we can use the universal specifier here if we want:

```suggestion
  // All members are initialized to 0 or NULL by C99 6.7.8/10.
  static const rmw_discovery_options_t result;
```

2024-09-12 17:17 UTC, clalancette commented on rmw/src/discovery_options.c
> +  };
```suggestion
```

2024-09-12 19:49 UTC, fujitatomoya commented on rmw/src/discovery_options.c
>      .static_peers_count = 0,
i was thinking that once `RMW_AUTOMATIC_DISCOVERY_RANGE_NOT_SET` enum is updated to another value in the future, this breaks easily. (that i think we should do that but guaranteed.) So that was my intention to leave this here. (i guess original author though about this in the same way)

2024-09-12 22:06 UTC, clalancette commented on rmw/src/discovery_options.c
>      .static_peers_count = 0,
While that is true, that shouldn't matter here.  This is the `get_zero_initialized` function, so it should always return 0 (in my opinion).

2024-09-12 22:45 UTC, fujitatomoya commented on rmw/src/discovery_options.c
>      .static_peers_count = 0,
yeah `RMW_AUTOMATIC_DISCOVERY_RANGE_NOT_SET ` should have been used with `xxx_get_default_option`. that is what i will do with the another patch, i am okay with 0 init then.

2024-09-12 22:48 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21834)](http://ci.ros2.org/job/ci_linux/21834/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16104)](http://ci.ros2.org/job/ci_linux-aarch64/16104/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1336)](http://ci.ros2.org/job/ci_linux-rhel/1336/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22543)](http://ci.ros2.org/job/ci_windows/22543/)

2024-09-12 22:48 UTC, fujitatomoya commented
@clalancette all comments are resolved, lgtm?

2024-09-13 15:21 UTC, clalancette approved these changes

2024-09-13 16:12 UTC, fujitatomoya commented
RHEL is unstable, https://ci.ros2.org/job/ci_linux-rhel/1336/testReport/.

* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1341)](http://ci.ros2.org/job/ci_linux-rhel/1341/)

2024-09-16 15:56 UTC, merged