get_zero_initialized_xxx functions return zero initialized structure.
ros2/rmw pull request #380
Opened 2024-10-11 01:19 UTC by fujitatomoya

replaces https://github.com/ros2/rmw/pull/379

and follow up https://github.com/ros2/rmw/pull/378

2024-10-11 01:25 UTC, fujitatomoya reviewed
@clalancette can you take a look?

2024-10-11 01:25 UTC, fujitatomoya commented on rmw/src/event.c
> -    .event_type = RMW_EVENT_INVALID
actually this is not zero, but it will be no problem since rmw implementation updates the event_type with `rmw_publisher_event_init` and `rmw_subscription_event_init`.

2024-10-11 01:25 UTC, fujitatomoya commented on rmw/src/init_options.c
> -    .discovery_options = {RMW_AUTOMATIC_DISCOVERY_RANGE_NOT_SET, 0},
RMW_AUTOMATIC_DISCOVERY_RANGE_NOT_SET is zero.

2024-10-11 01:25 UTC, fujitatomoya commented on rmw/src/init_options.c
> -    .security_options = {RMW_SECURITY_ENFORCEMENT_PERMISSIVE, NULL},
RMW_SECURITY_ENFORCEMENT_PERMISSIVE is zero.

2024-10-11 01:25 UTC, fujitatomoya commented on rmw/src/init_options.c
> -    .domain_id = RMW_DEFAULT_DOMAIN_ID,
This will be written by rmw implementation via `rmw_init_options_init`, so it should be no problem.

2024-10-11 01:26 UTC, fujitatomoya commented
Pulls: ros2/rmw#380
Gist: https://gist.githubusercontent.com/fujitatomoya/511ae3290eaf698932f4a234e72c2db4/raw/51a991ad78ac2e0c9e5df8765db826a6ff8e014a/ros2.repos
BUILD args:  --packages-above-and-dependencies rmw
TEST args:  --packages-above rmw
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14692
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21980)](http://ci.ros2.org/job/ci_linux/21980/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16245)](http://ci.ros2.org/job/ci_linux-aarch64/16245/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1494)](http://ci.ros2.org/job/ci_linux-rhel/1494/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22710)](http://ci.ros2.org/job/ci_windows/22710/)

2024-10-11 11:45 UTC, clalancette commented on rmw/src/event.c
> -    .event_type = RMW_EVENT_INVALID
I'm actually thinking that we should break the ABI of `RMW_EVENT_INVALID`, and revamp it.  That particular constant is actually weird, in that `INVALID` is being used as the enum "max".  Further, by setting this to zero, it means that by default the `event_type` will be `RMW_EVENT_LIVELINESS_CHANGED`, which is kind of weird.  

While this is a mostly theoretical problem (as mentioned, the `event_init` methods will change this), I think it would be best if we actually made `RMW_EVENT_INVALID` 0, and then introduced an `RMW_EVENT_MAX` (or similar) enum.  Unfortunately, this will require updates to both `rmw_connextdds` and `rmw_fastrtps` (since they both use `RMW_EVENT_INVALID` to create some static arrays), but I think the overall thing will be better.

@fujitatomoya Does that make sense?  What do you think?

2024-10-11 11:45 UTC, clalancette commented on rmw/test/test_event.cpp
> +  EXPECT_EQ(0u, actual.event_type);
If we make the change I suggest above, then we won't actually need this change.

2024-10-11 11:45 UTC, clalancette commented on rmw/test/test_event.cpp
> +  EXPECT_EQ(0u, event.event_type);
Same here.

2024-10-11 15:29 UTC, fujitatomoya commented on rmw/src/event.c
> -    .event_type = RMW_EVENT_INVALID
totally agree, lets do that!

2024-10-11 15:50 UTC, fujitatomoya commented
@clalancette totally agree with your review comments, thanks. all comments are resolved, ready to review.

2024-10-11 15:54 UTC, fujitatomoya commented
Pulls: ros2/rmw#380, ros2/rmw_connextdds#162, ros2/rmw_fastrtps#785
Gist: https://gist.githubusercontent.com/fujitatomoya/287bc10787b6388b8c13bf6fdfa4d974/raw/ec909bd20c342c882a27450c57dc05ce62d209b5/ros2.repos
BUILD args:  --packages-above-and-dependencies rmw rmw_connextdds_common rmw_fastrtps_shared_cpp
TEST args:  --packages-above rmw rmw_connextdds_common rmw_fastrtps_shared_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14697
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21985)](http://ci.ros2.org/job/ci_linux/21985/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16250)](http://ci.ros2.org/job/ci_linux-aarch64/16250/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1499)](http://ci.ros2.org/job/ci_linux-rhel/1499/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22717)](http://ci.ros2.org/job/ci_windows/22717/)

2024-10-16 21:43 UTC, fujitatomoya commented
Pulls: ros2/rmw#380, ros2/rmw_fastrtps#785, ros2/rmw_connextdds#162, ros2/rmw_cyclonedds#518
Gist: https://gist.githubusercontent.com/fujitatomoya/a5a27e64c97e3b687ed9c85018393aef/raw/398849da025367226392ce4eacd4f8114a09b768/ros2.repos
BUILD args:  --packages-above-and-dependencies rmw rmw_fastrtps_shared_cpp rmw_connextdds_common rmw_cyclonedds_cpp
TEST args:  --packages-above rmw rmw_fastrtps_shared_cpp rmw_connextdds_common rmw_cyclonedds_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14711
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22003)](http://ci.ros2.org/job/ci_linux/22003/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16264)](http://ci.ros2.org/job/ci_linux-aarch64/16264/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1517)](http://ci.ros2.org/job/ci_linux-rhel/1517/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22736)](http://ci.ros2.org/job/ci_windows/22736/)

2024-10-17 03:28 UTC, fujitatomoya commented
the CI failure is missing https://github.com/ros2/rmw_fastrtps/commit/8fd6f3cbf2392e77510f77f3e98e106d0b5d1443, we need to rebase and restart the CI.

2024-10-17 03:29 UTC, fujitatomoya commented
Pulls: ros2/rmw#380, ros2/rmw_fastrtps#785, ros2/rmw_connextdds#162, ros2/rmw_cyclonedds#518
Gist: https://gist.githubusercontent.com/fujitatomoya/6abc026e02c2c115a589c04c79e23c39/raw/398849da025367226392ce4eacd4f8114a09b768/ros2.repos
BUILD args:  --packages-above-and-dependencies rmw rmw_fastrtps_shared_cpp rmw_connextdds_common rmw_cyclonedds_cpp
TEST args:  --packages-above rmw rmw_fastrtps_shared_cpp rmw_connextdds_common rmw_cyclonedds_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14714
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22006)](http://ci.ros2.org/job/ci_linux/22006/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16267)](http://ci.ros2.org/job/ci_linux-aarch64/16267/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1529)](http://ci.ros2.org/job/ci_linux-rhel/1529/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22741)](http://ci.ros2.org/job/ci_windows/22741/)

2024-10-17 21:13 UTC, fujitatomoya commented
Linux-aarch64 and Windows CIs were not started successfully with some reason, and RHEL is known issue. i will start the CI for all platform once again.

2024-10-17 21:14 UTC, fujitatomoya commented
Pulls: ros2/rmw#380, ros2/rmw_fastrtps#785, ros2/rmw_connextdds#162, ros2/rmw_cyclonedds#518
Gist: https://gist.githubusercontent.com/fujitatomoya/82891bb189950fefcf68c0f191365af1/raw/398849da025367226392ce4eacd4f8114a09b768/ros2.repos
BUILD args:  --packages-above-and-dependencies rmw rmw_fastrtps_shared_cpp rmw_connextdds_common rmw_cyclonedds_cpp
TEST args:  --packages-above rmw rmw_fastrtps_shared_cpp rmw_connextdds_common rmw_cyclonedds_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14720
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22014)](http://ci.ros2.org/job/ci_linux/22014/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16274)](http://ci.ros2.org/job/ci_linux-aarch64/16274/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1536)](http://ci.ros2.org/job/ci_linux-rhel/1536/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22748)](http://ci.ros2.org/job/ci_windows/22748/)

2024-10-18 17:23 UTC, fujitatomoya commented
Pulls: ros2/rmw#380, ros2/rmw_fastrtps#785, ros2/rmw_connextdds#162, ros2/rmw_cyclonedds#518
Gist: https://gist.githubusercontent.com/fujitatomoya/16961ebf1f4059173817c9730b42d685/raw/398849da025367226392ce4eacd4f8114a09b768/ros2.repos
BUILD args:  --packages-above-and-dependencies rmw rmw_fastrtps_shared_cpp rmw_connextdds_common rmw_cyclonedds_cpp
TEST args:  --packages-above rmw rmw_fastrtps_shared_cpp rmw_connextdds_common rmw_cyclonedds_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14722
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22020)](http://ci.ros2.org/job/ci_linux/22020/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16276)](http://ci.ros2.org/job/ci_linux-aarch64/16276/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1538)](http://ci.ros2.org/job/ci_linux-rhel/1538/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22750)](http://ci.ros2.org/job/ci_windows/22750/)

2024-10-19 21:27 UTC, fujitatomoya commented
Pulls: ros2/rmw#380, ros2/rmw_fastrtps#785, ros2/rmw_connextdds#162, ros2/rmw_cyclonedds#518
Gist: https://gist.githubusercontent.com/fujitatomoya/065211cb8895027ee0a710a50b6a9851/raw/398849da025367226392ce4eacd4f8114a09b768/ros2.repos
BUILD args:  --packages-above-and-dependencies rmw rmw_fastrtps_shared_cpp rmw_connextdds_common rmw_cyclonedds_cpp
TEST args:  --packages-above rmw rmw_fastrtps_shared_cpp rmw_connextdds_common rmw_cyclonedds_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14726
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22024)](http://ci.ros2.org/job/ci_linux/22024/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16280)](http://ci.ros2.org/job/ci_linux-aarch64/16280/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1542)](http://ci.ros2.org/job/ci_linux-rhel/1542/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22754)](http://ci.ros2.org/job/ci_windows/22754/)

2024-10-22 09:14 UTC, fujitatomoya commented
@clalancette can you take an another look at this?

2024-11-19 01:24 UTC, fujitatomoya commented
@clalancette i addressed all of the comments, please take a look at them when you have time.

2024-12-01 23:04 UTC, fujitatomoya commented
@clalancette friendly ping!

2025-02-03 21:48 UTC, fujitatomoya commented
@mjcarroll @ahcorde @jmachowinski either of you, can you review this?
CC: @clalancette

2025-02-04 15:59 UTC, jmachowinski requested changes

2025-02-04 15:59 UTC, jmachowinski commented on rmw/include/rmw/event.h
> +  RMW_EVENT_INVALID,
```suggestion
  // must be zero or rmw_get_zero_initialized_event will break
  RMW_EVENT_INVALID = 0,
```

2025-02-04 15:59 UTC, jmachowinski commented on rmw/include/rmw/event.h
> +  RMW_EVENT_INVALID,
Is there a test, that will check, if RMW_EVENT_INVALID is actually zero ?

2025-02-04 15:59 UTC, jmachowinski commented on rmw/test/test_init_options.cpp
> +  EXPECT_EQ(options.enclave, nullptr);
```suggestion
  EXPECT_EQ(options.enclave, nullptr);
  EXPECT_EQ(options.security_options.enforce_security, RMW_SECURITY_ENFORCEMENT_PERMISSIVE);
  EXPECT_EQ(options.security_options.security_root_path, nullptr);
  EXPECT_EQ(options.discovery_options.automatic_discovery_range, RMW_AUTOMATIC_DISCOVERY_RANGE_NOT_SET);
  .
  .
  .
```

2025-02-04 22:14 UTC, fujitatomoya commented on rmw/include/rmw/event.h
> +  RMW_EVENT_INVALID,
fixed in https://github.com/ros2/rmw/pull/380/commits/92f1486a0df448fb389283ea70a94f5a2f5506fd

2025-02-04 22:14 UTC, fujitatomoya commented on rmw/test/test_init_options.cpp
> +  EXPECT_EQ(options.enclave, nullptr);
fixed in https://github.com/ros2/rmw/pull/380/commits/92f1486a0df448fb389283ea70a94f5a2f5506fd

2025-02-04 22:23 UTC, fujitatomoya commented
Pulls: ros2/rmw#380, ros2/rmw_connextdds#162, ros2/rmw_fastrtps#785, ros2/rmw_cyclonedds#518
Gist: https://gist.githubusercontent.com/fujitatomoya/29f611cd228c356fd94dc372b220b0ba/raw/5dc544053744c46415545fe90336becf878d9765/ros2.repos
BUILD args:  --packages-above-and-dependencies rmw rmw_fastrtps_shared_cpp rmw_connextdds_common rmw_cyclonedds_cpp
TEST args:  --packages-above rmw rmw_fastrtps_shared_cpp rmw_connextdds_common rmw_cyclonedds_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15120
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22450)](http://ci.ros2.org/job/ci_linux/22450/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16702)](http://ci.ros2.org/job/ci_linux-aarch64/16702/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1978)](http://ci.ros2.org/job/ci_linux-rhel/1978/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23239)](http://ci.ros2.org/job/ci_windows/23239/)

2025-02-04 22:24 UTC, fujitatomoya commented
@jmachowinski requesting final review, i have addressed your comments.

besides, CI is on run with all dependent PRs.

2025-02-04 23:26 UTC, mjcarroll approved these changes

2025-02-05 08:53 UTC, jmachowinski approved these changes

2025-02-05 15:41 UTC, merged